spring:
  application:
    name: mcp-test-service
  ai:
    mcp:
      server:
        enabled: true
        name: mcp-test-service
        version: 0.1.0
        type: SYNC
        protocol: SSE
        web-base-path: /mcp
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message

server:
  port: 18080

management:
  endpoints:
    web:
      exposure:
        include: health,info
